<?php

namespace Doctors\AdminBundle\Repository;

/**
 * DoctorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDoctorNumbers()
    {
        return $this->createQueryBuilder('d')
            ->select("COUNT(d)")
            ->getQuery()
            ->getSinglescalarResult();
    }
}
