<?php

namespace Doctors\AdminBundle\Repository;

/**
 * TokenUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenUserRepository extends \Doctrine\ORM\EntityRepository
{
}
