<?php

namespace Doctors\AdminBundle\Repository;

/**
 * TokenDoctorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenDoctorRepository extends \Doctrine\ORM\EntityRepository
{
}
